package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pjrt_c_api",
    hdrs = [
        "c_api_decl.h",
        "pjrt_c_api.h",
        "pjrt_c_api_tpu.h",
    ],
    visibility = ["//visibility:public"],
)
