cc_library(
    name = "byteswaparray",
    srcs = ["byte_swap_array.cc"],
    hdrs = ["byte_swap_array.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//itex/core/utils:byte_order",
        "//itex/core/utils:errors",
        "//itex/core/utils:status",
    ],
)
