filegroup(
    name = "itex_cpu_wrapper",
    srcs = [
        "itex_cpu_wrapper.cc",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "itex_gpu_wrapper",
    srcs = [
        "itex_gpu_wrapper.cc",
    ],
    visibility = ["//visibility:public"],
)
