filegroup(
    name = "itex_stream",
    srcs = [
        "cpu_stream.cc",
        "mkl_threadpool.h",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "itex_stream_omp",
    srcs = [
        "cpu_stream_omp.cc",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "mkl_threadpool",
    srcs = [
        "mkl_threadpool.h",
    ],
    visibility = ["//visibility:public"],
)
