package(default_visibility = ["//visibility:public"])

cc_library(
    name = "name_utils",
    srcs = ["utils/name_utils.cc"],
    hdrs = ["utils/name_utils.h"],
    deps = [
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:IR",
    ],
)
